---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r loading, warning=FALSE, message=FALSE}
library(magrittr)
library(readr)
library(dplyr)
library(ggplot2)

activity <- read_csv("activity.csv", col_types = list(col_integer(), col_date(), col_integer()))

activitybyday <- activity %>%
      group_by(date) %>%
      summarize(stepstotal = sum(steps))
activitybyinterval <- activity %>%
      group_by(interval) %>%
      summarize(stepsmean = mean(steps, na.rm = TRUE))
```

## What is mean total number of steps taken per day?
```{r histogram, warning=FALSE, message=FALSE}
activitybyday %>%
      ggplot(aes(x=stepstotal)) +
      geom_histogram(binwidth = 5000, aes(fill=..count..)) +
      labs(x = "Total number of steps per day", y = "Steps count")
summary(activitybyday)
activitybyday_mean <- summarize(activitybyday, mean = mean(stepstotal, na.rm = TRUE)) %>%
      as.matrix() %>%
      as.vector() %>%
      as.integer()
activitybyday_median <- summarize(activitybyday, median = median(stepstotal, na.rm = TRUE)) %>%
      as.matrix() %>%
      as.vector()
print(paste("Mean of total number of steps per day (integer): ", activitybyday_mean))
print(paste("Median of total number of steps per day (integer): ", activitybyday_median))
```

## What is the average daily activity pattern?
```{r activity, warning=FALSE, message=FALSE}
activitybyinterval %>%
      ggplot(aes(x=interval, y=stepsmean)) +
      geom_line() +
      labs(x = "5-min interval", y = "Mean steps count")
summary(activitybyinterval)
activitybyinterval_max <- summarize(activitybyinterval, max = which.max(stepsmean)) %>%
      unlist() %>%
      as.vector() %>%
      activitybyinterval[., 1] %>%
      as.matrix() %>%
      as.vector()
print(paste("Interval ", activitybyinterval_max, " contains the maximum number of steps."))
```


## Imputing missing values
1. Calculate and report the total number of missing values in the dataset.
```{r NA, warning=FALSE, message=FALSE}
print(paste("The original dataset contains ", sum(is.na(activity)), " NAs."))
```

## Are there differences in activity patterns between weekdays and weekends?
